"use client";
import { ImageUpload } from "@/components/admin/image-upload";
import { PostStatusBadge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Field, Input, Select, Textarea } from "@/components/ui/field";
import { GENERATED_BY } from "@/lib/constants";
import type { PublishCheck } from "@/lib/post-status";
import type { AuthorOption, CategoryOption, SerializedPost } from "./serialize";
import { TagInput } from "./tag-input";

/** Patch object or functional updater (use the updater when several async callbacks append to the same array). */
export type EditorUpdate<V> = Partial<V> | ((current: V) => Partial<V>);

export type SidebarValues = {
  categoryId: string;
  authorId: string;
  generatedBy: (typeof GENERATED_BY)[number];
  affectedBuilds: string[];
  testedOnBuild: string;
  lastVerifiedAt: string;
  metaTitle: string;
  metaDescription: string;
  featuredImage: string;
  screenshots: string[];
  sourceUrls: string;
};

type Props = {
  /** Changes after each server action; remounts the selects (see post-editor.tsx). */
  selectEpoch?: number;
  values: SidebarValues;
  update: (patch: EditorUpdate<SidebarValues>) => void;
  categories: CategoryOption[];
  authors: AuthorOption[];
  errors: Record<string, string>;
  post: SerializedPost | null;
  publishCheck: PublishCheck | null;
};

const META_TITLE_MAX = 70;
const META_DESCRIPTION_MAX = 170;

function Counter({ length, max }: { length: number; max: number }) {
  return <span className={length > max ? "font-medium text-red-600" : undefined}>{`${length}/${max}`}</span>;
}

export function PostSidebar({ values, update, categories, authors, errors, post, publishCheck, selectEpoch = 0 }: Props) {
  return (
    <aside className="space-y-4">
      {post ? (
        <Card title="Status">
          <div className="flex items-center justify-between">
            <PostStatusBadge status={post.status} />
            <span className="text-xs text-zinc-500">{post.generatedBy === "AI" ? "AI generated" : "Written by hand"}</span>
          </div>
          {publishCheck ? (
            <div className="mt-3 space-y-2">
              {publishCheck.errors.length ? (
                <ul className="space-y-1 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-800">
                  <li className="font-medium">Blocks publishing</li>
                  {publishCheck.errors.map((e) => (
                    <li key={e}>• {e}</li>
                  ))}
                </ul>
              ) : (
                <p className="rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-900">Passes the publish check.</p>
              )}
              {publishCheck.warnings.length ? (
                <ul className="space-y-1 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-900">
                  <li className="font-medium">Warnings</li>
                  {publishCheck.warnings.map((w) => (
                    <li key={w}>• {w}</li>
                  ))}
                </ul>
              ) : null}
              <p className="text-[11px] text-zinc-400">Checked against the last saved version.</p>
            </div>
          ) : null}
        </Card>
      ) : null}

      <Card title="Classification">
        <div className="space-y-3">
          <Field label="Category" htmlFor="post-category" error={errors.categoryId}>
            <Select key={`category-${selectEpoch}`} id="post-category" name="categoryId" value={values.categoryId} onChange={(e) => update({ categoryId: e.target.value })}>
              <option value="">Select a category…</option>
              {categories.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.name}
                </option>
              ))}
            </Select>
          </Field>
          <Field label="Author" htmlFor="post-author" error={errors.authorId}>
            <Select key={`author-${selectEpoch}`} id="post-author" name="authorId" value={values.authorId} onChange={(e) => update({ authorId: e.target.value })}>
              <option value="">Select an author…</option>
              {authors.map((a) => (
                <option key={a.id} value={a.id}>
                  {a.name}
                </option>
              ))}
            </Select>
          </Field>
          <Field label="Generated by" htmlFor="post-generated-by" error={errors.generatedBy}>
            <Select
              key={`generated-by-${selectEpoch}`}
              id="post-generated-by"
              name="generatedBy"
              value={values.generatedBy}
              onChange={(e) => update({ generatedBy: e.target.value === "AI" ? "AI" : "HUMAN" })}
            >
              {GENERATED_BY.map((g) => (
                <option key={g} value={g}>
                  {g === "AI" ? "AI (pipeline)" : "Human"}
                </option>
              ))}
            </Select>
          </Field>
        </div>
      </Card>

      <Card title="Verification">
        <div className="space-y-3">
          <Field label="Affected builds" htmlFor="post-affected-builds" hint="Enter or comma adds" error={errors.affectedBuilds} help="Shown as badges under the title.">
            <TagInput id="post-affected-builds" name="affectedBuilds" value={values.affectedBuilds} onChange={(v) => update({ affectedBuilds: v })} placeholder="Type a version and press Enter" />
          </Field>
          <Field label="Tested on build" htmlFor="post-tested-on" error={errors.testedOnBuild} help="Empty shows “Verified: pending” on the public page.">
            <Input id="post-tested-on" name="testedOnBuild" value={values.testedOnBuild} onChange={(e) => update({ testedOnBuild: e.target.value })} maxLength={60} placeholder="Build you reproduced the fix on" />
          </Field>
          <Field label="Last verified" htmlFor="post-last-verified" error={errors.lastVerifiedAt}>
            <Input id="post-last-verified" type="date" name="lastVerifiedAt" value={values.lastVerifiedAt} onChange={(e) => update({ lastVerifiedAt: e.target.value })} />
          </Field>
        </div>
      </Card>

      <Card title="SEO">
        <div className="space-y-3">
          <Field label="Meta title" htmlFor="post-meta-title" hint={<Counter length={values.metaTitle.length} max={META_TITLE_MAX} />} error={errors.metaTitle}>
            <Input id="post-meta-title" name="metaTitle" value={values.metaTitle} onChange={(e) => update({ metaTitle: e.target.value })} placeholder="Defaults to the title on the public page if empty" />
          </Field>
          <Field
            label="Meta description"
            htmlFor="post-meta-description"
            hint={<Counter length={values.metaDescription.length} max={META_DESCRIPTION_MAX} />}
            error={errors.metaDescription}
          >
            <Textarea
              id="post-meta-description"
              name="metaDescription"
              value={values.metaDescription}
              onChange={(e) => update({ metaDescription: e.target.value })}
              className="min-h-20"
              placeholder="One or two sentences for the search snippet"
            />
          </Field>
        </div>
      </Card>

      <Card title="Images">
        <div className="space-y-4">
          <Field label="Featured image" htmlFor="post-featured-image" error={errors.featuredImage} help="1200px+ wide for Google Discover. The pipeline generates one if empty.">
            <div className="space-y-2">
              {values.featuredImage ? (
                <div className="overflow-hidden rounded-md border border-zinc-200 bg-zinc-50">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={values.featuredImage} alt="Featured" className="block max-h-40 w-full object-cover" />
                </div>
              ) : null}
              <div className="flex items-center gap-2">
                <ImageUpload folder="featured" label="Upload featured image" onUploaded={(url) => update({ featuredImage: url })} />
                {values.featuredImage ? (
                  <Button size="sm" intent="ghost" onClick={() => update({ featuredImage: "" })}>
                    Clear
                  </Button>
                ) : null}
              </div>
              <Input id="post-featured-image" name="featuredImage" value={values.featuredImage} onChange={(e) => update({ featuredImage: e.target.value })} placeholder="/uploads/featured/… or https://…" />
            </div>
          </Field>

          <div>
            <p className="mb-1 flex items-baseline justify-between text-sm font-medium text-zinc-800">
              <span>Screenshots</span>
              <span className="text-xs font-normal text-zinc-500">{values.screenshots.length} uploaded</span>
            </p>
            <input type="hidden" name="screenshots" value={JSON.stringify(values.screenshots)} />
            {values.screenshots.length ? (
              <ul className="mb-2 grid grid-cols-3 gap-2">
                {values.screenshots.map((url) => (
                  <li key={url} className="group relative overflow-hidden rounded-md border border-zinc-200 bg-zinc-50">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={url} alt="" className="block aspect-[4/3] w-full object-cover" />
                    <button
                      type="button"
                      onClick={() => update((v) => ({ screenshots: v.screenshots.filter((s) => s !== url) }))}
                      aria-label="Remove screenshot"
                      className="absolute top-1 right-1 rounded bg-white/90 px-1.5 text-xs text-zinc-700 shadow-xs hover:bg-white hover:text-red-600"
                    >
                      ×
                    </button>
                  </li>
                ))}
              </ul>
            ) : null}
            {/* Multi-file uploads call onUploaded once per file from the same closure: append functionally so no file is lost. */}
            <ImageUpload
              folder="screenshots"
              multiple
              label="Upload screenshots"
              onUploaded={(url) => update((v) => ({ screenshots: v.screenshots.includes(url) ? v.screenshots : [...v.screenshots, url] }))}
            />
            {errors.screenshots ? (
              <p className="mt-1 text-xs text-red-600" role="alert">
                {errors.screenshots}
              </p>
            ) : (
              <p className="mt-1 text-xs text-zinc-500">Real screenshots from the build you tested on. At least one is expected before publishing.</p>
            )}
          </div>
        </div>
      </Card>

      <Card title="Sources">
        <Field label="Source URLs" htmlFor="post-source-urls" hint="one per line" error={errors.sourceUrls} help="Official docs first. Only facts from these sources belong in the post.">
          <Textarea
            id="post-source-urls"
            name="sourceUrls"
            value={values.sourceUrls}
            onChange={(e) => update({ sourceUrls: e.target.value })}
            className="min-h-24 font-mono text-xs"
            placeholder="https://…"
            spellCheck={false}
          />
        </Field>
      </Card>

      {post && (post.qualityScore !== null || post.qualityNotes) ? (
        <Card title="Quality gate">
          {post.qualityScore !== null ? (
            <p className="text-sm">
              Score: <span className={`font-semibold ${post.qualityScore >= 85 ? "text-emerald-700" : "text-amber-700"}`}>{post.qualityScore}/100</span>
            </p>
          ) : null}
          {post.qualityNotes ? <p className="mt-1 whitespace-pre-wrap text-xs text-zinc-600">{post.qualityNotes}</p> : null}
        </Card>
      ) : null}

      {post ? (
        <Card title="Timestamps">
          <dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-1 text-xs">
            <dt className="text-zinc-500">Created</dt>
            <dd className="text-zinc-800">
              <time dateTime={post.createdAt}>{post.createdAtLabel}</time>
            </dd>
            <dt className="text-zinc-500">Updated</dt>
            <dd className="text-zinc-800">
              <time dateTime={post.updatedAt}>{post.updatedAtLabel}</time>
            </dd>
            <dt className="text-zinc-500">Published</dt>
            <dd className="text-zinc-800">{post.publishedAt ? <time dateTime={post.publishedAt}>{post.publishedAtLabel}</time> : post.publishedAtLabel}</dd>
          </dl>
        </Card>
      ) : null}
    </aside>
  );
}
