/**
 * Orchestrates the per-post illustration set: which Settings screen(s) a post is about, then
 * turning those into stored image files and inline markdown. See screens.ts for the screen
 * catalogue and svg-kit.ts/shell.ts/content.ts for the drawing primitives.
 *
 * Images are never written to disk here. Each illustration is a URL to /api/illustration (see
 * src/app/api/illustration/route.ts), which renders and rasterises the same SVG templates
 * on demand and caches the result forever — the same approach this app already uses for the
 * branded /api/og card. That also means a post generated by a local script and one generated by
 * the deployed app produce byte-identical, always-reachable images; there is no file to ship
 * between the two.
 */
import { splitH2Sections } from "@/lib/post-utils";
import { CANVAS } from "./shell";
import { captionFor, detectScreenForText, DEFAULT_SCREEN, type ScreenId } from "./screens";

export const FEATURED_SIZE = { width: CANVAS.width, height: CANVAS.height } as const; // 1200x630, matches the site's OG image convention
export const INLINE_SIZE = { width: 900, height: Math.round((900 * CANVAS.height) / CANVAS.width) } as const; // same 1200:630 aspect, smaller

/** Headings that actually walk a reader through a UI action — the only sections eligible for an inline illustration. */
const INSTRUCTIONAL_HEADING = /^(method\s+\d+|steps|how to get it)\b/i;

export type IllustrationPick = { screenId: ScreenId; highlight: number; sectionIndex: number };
export type IllustrationPlan = { featured: { screenId: ScreenId; highlight: number }; inline: IllustrationPick[] };

/**
 * Decide which screen(s) to draw for a post, purely from its title/body text. No I/O — safe to
 * unit test directly. Inline picks are capped at 2 and always land on an instructional H2
 * (Method N / Steps / How to get it), preferring sections that clearly name a specific screen.
 */
export function planIllustrations(input: { title: string; body: string }): IllustrationPlan {
  const { sections } = splitH2Sections(input.body);
  const instructional = sections.filter((s) => INSTRUCTIONAL_HEADING.test(s.heading.trim()));

  const detected = instructional
    .map((s) => ({ sectionIndex: s.index, screenId: detectScreenForText(`${s.heading}\n${s.content}`) }))
    .filter((d): d is { sectionIndex: number; screenId: ScreenId } => d.screenId !== null);

  const overall = detectScreenForText(`${input.title}\n${input.body.slice(0, 400)}`) ?? DEFAULT_SCREEN;

  let picks: IllustrationPick[];
  if (detected.length > 0) {
    picks = detected.slice(0, 2).map((d, i) => ({ ...d, highlight: i }));
  } else if (instructional.length > 0) {
    // Nothing named a specific screen — still show the reader *a* Settings screen, anchored to the first step.
    picks = [{ sectionIndex: instructional[0].index, screenId: overall, highlight: 0 }];
  } else {
    picks = [];
  }

  const featured = picks[0] ? { screenId: picks[0].screenId, highlight: picks[0].highlight } : { screenId: overall, highlight: 0 };
  return { featured, inline: picks };
}

/** Build the /api/illustration URL for one rendered screen. Deterministic — same inputs, same URL, forever. */
export function illustrationUrl(screenId: ScreenId, highlight: number, width: number, height: number): string {
  const params = new URLSearchParams({ screen: screenId, highlight: String(highlight), w: String(width), h: String(height) });
  return `/api/illustration?${params.toString()}`;
}

/** Marker left in a post's body once it has inline illustrations, so backfills are idempotent. */
export const ILLUSTRATION_MARKER = "Illustration:";
/** Marker of the old (broken) file-based scheme, used to find and repair posts backfilled before this fix. */
export const LEGACY_UPLOAD_MARKER = "/uploads/illustrations/";

/**
 * Generate the full illustration set for a post: one featured/OG image URL, and up to two inline
 * image URLs spliced into the body right under the relevant Method/Steps heading, each captioned
 * "Illustration: ..." (never "Screenshot"). Pure — no network, no filesystem, safe to call from
 * anywhere (the pipeline, the backfill script, or a future editor "regenerate" button).
 */
export function generateIllustrationsForPost(input: { title: string; body: string }): { featuredImage: string; body: string } {
  const plan = planIllustrations(input);
  const featuredImage = illustrationUrl(plan.featured.screenId, plan.featured.highlight, FEATURED_SIZE.width, FEATURED_SIZE.height);

  // Insert from the last section to the first so earlier line numbers stay valid as we splice.
  let body = input.body;
  const byIndexDesc = [...plan.inline].sort((a, b) => b.sectionIndex - a.sectionIndex);
  for (const pick of byIndexDesc) {
    const url = illustrationUrl(pick.screenId, pick.highlight, INLINE_SIZE.width, INLINE_SIZE.height);
    const caption = captionFor(pick.screenId);
    body = insertAfterHeading(body, pick.sectionIndex, `![${caption}](${url})\n\n*${caption}*`);
  }

  return { featuredImage, body };
}

/** Strip a previously-inserted illustration block (image + italic caption) so a post can be re-planned cleanly. */
export function stripIllustrations(body: string): string {
  const block = /!\[Illustration:[^\]]*\]\([^)]*\)\n{1,3}\*Illustration:[^*]*\*\n{0,3}/g;
  return body.replace(block, "").replace(/\n{3,}/g, "\n\n");
}

/** Splice markdown right after an H2 heading line, before whatever content already follows it. */
function insertAfterHeading(body: string, sectionIndex: number, snippet: string): string {
  const lines = body.split(/\r?\n/);
  const { sections } = splitH2Sections(body);
  const s = sections[sectionIndex];
  if (!s) return body;
  const before = lines.slice(0, s.start + 1);
  const after = lines.slice(s.start + 1);
  return [...before, "", snippet.trim(), "", ...after].join("\n").replace(/\n{3,}/g, "\n\n");
}
